<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
        
        <title>De Ruiter Kruiswoordpuzzel</title>
        
        <script src="https://www.google.com/jsapi"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js"></script>
        <script type="text/javascript" src="js/image_search.js"></script>
        <script type="text/javascript" src="js/kruiswoord.js"></script>
        
        <link type="text/css" rel="stylesheet" href="css/normalize.css" />
        <link type="text/css" rel="stylesheet" href="css/kruiswoord.css" />
    </head>
    <body>
        <div id="branding"></div><br />
        <div id="content"></div>
    	<br style="clear:both;" />
    	<div id="descriptions">
    		<ol>
    			<li>gastank</li>
    			<li>woord</li>
    			<li>verlies</li>
    			<li>poep</li>
    		</ol>
    	</div>
    	<div id="puzzle_container">
    		<?php echo $puzzle->render(); ?>
        </div>
    </body>
</html>